image: docker
services:
- docker:dind

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - deploy
  
  
build_dialcrowd_server:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE --pull .
    - docker push $CI_REGISTRY_IMAGE

      #build_dialcrowd_client:
      #  stage: build
      #  script:
      #    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      #    - docker build -t $CI_REGISTRY_IMAGE/client --pull dialcrowd/client/
      #    - docker push $CI_REGISTRY_IMAGE/client

deploy_production:
  image: alpine
  stage: deploy
  environment: production
  tags:
    - dsml
  before_script:
    - apk add --no-cache openssh
    - eval "$(ssh-agent -s)"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh/
    - ssh-keyscan -H 'castle.cs.hhu.de' > ~/.ssh/known_hosts
  script:
    - ssh root@castle.cs.hhu.de
  only:
    - master
      
