image: docker
services:
- docker:dind

stages:
  - build
  
build_dialcrowd_server:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE --pull .
    - docker push $CI_REGISTRY_IMAGE